param(
    [string]$Path = '.\aiwf_vllm_launch_profile.json',
    [string]$Model = 'Qwen/Qwen2.5-1.5B-Instruct',
    [int]$Port = 8000,
    [double]$GpuMemoryUtilization = 0.85,
    [int]$MaxModelLen = 8192
)
$profile = [ordered]@{
  engine = 'vllm'
  model = $Model
  host = '127.0.0.1'
  port = $Port
  gpu_memory_utilization = $GpuMemoryUtilization
  max_model_len = $MaxModelLen
  api_base = "http://127.0.0.1:$Port/v1"
  notes = 'Generated by AIWF. Tune for GPU VRAM and model size before sharing.'
}
$profile | ConvertTo-Json -Depth 5 | Out-File -Encoding UTF8 $Path
Write-Host "Wrote $Path"
